POST localhost:8080/api/v1/admin/topics
Content-Type: application/json
Authorization: Beerer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiUk9MRSI6W3siaWQiOjEsInRpdGxlIjoiUk9MRV9VU0VSIn1dLCJpc3MiOiJRdWVzdGlmeSIsImlhdCI6MTcxMjg2NDY5MiwiZXhwIjoxNzEyOTAwNjkyfQ.oTHzTmYMj6fqcAI0B63vkmUwPzASVGlLWud0dX2-gng

{
  "name": "Spring"
}

###
GET localhost:8080/api/v1/admin/topics/1
Content-Type: application/json
Authorization: Beerer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiUk9MRSI6W3siaWQiOjEsInRpdGxlIjoiUk9MRV9VU0VSIn1dLCJpc3MiOiJRdWVzdGlmeSIsImlhdCI6MTcxMjg2NDY5MiwiZXhwIjoxNzEyOTAwNjkyfQ.oTHzTmYMj6fqcAI0B63vkmUwPzASVGlLWud0dX2-gng

